FROM node:24-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm

ARG VITE_API_EXPORT_MAX_DAYS
ARG VITE_API_ALL_OPERATORS_CATALOG

COPY pnpm-lock.yaml pnpm-workspace.yaml ./
COPY package.json ./
COPY apps/web/ ./apps/web/

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm --filter web build

FROM registry.access.redhat.com/ubi9/nginx-124

COPY apps/web/nginx.conf /tmp/src/nginx-default-cfg/
COPY --from=builder /app/apps/web/dist /tmp/src/

USER root
RUN chown -R 1001:0 /tmp/src
USER 1001

RUN /usr/libexec/s2i/assemble

EXPOSE 8080

CMD /usr/libexec/s2i/run
