services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Containerfile
    container_name: pullsar-api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./apps/web/Containerfile
    container_name: pullsar-web
    ports:
      - "5173:80"
    depends_on:
      - api

  db:
    image: docker.io/library/postgres:17
    container_name: pullsar-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
