---
all:
  children:
    pullsar_stage:
      hosts:
        stage_host:
          ansible_connection: local
          ansible_host: localhost
    pullsar_prod:
      hosts:
        prod_host:
          ansible_connection: local
          ansible_host: localhost
