pullsar-stage:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    project_namespace: "pullsar-stage"
    api_replicas: 1
    web_replicas: 1
    api_all_operators_catalog: "All Operators"
    api_export_max_days: 30
    worker_catalogs:
      - name: "redhat-marketplace-index"
        base_image: "registry.redhat.io/redhat/redhat-marketplace-index"

    postgres_volume_capacity: "2Gi"
    postgres_version: "15-el8"
    postgres_memory_limit: "512Mi"
