---
- name: "Deploy Pullsar application to the '{{ env }}' environment"
  hosts: "pullsar_{{ env }}"
  connection: local
  gather_facts: false

  vars_files:
    - "../vaults/{{ env }}/secrets.yml"

  environment:
    K8S_AUTH_API_KEY: "{{ ocp_token }}"
    K8S_AUTH_HOST: "{{ ocp_host }}"

  roles:
    - role: project_setup
      tags: always

    - role: app
      tags: app
