apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: "{{ namespace }}"
spec:
  selector:
    app: pullsar-api
  ports:
  - name: 8000-tcp
    protocol: TCP
    port: 8000
    targetPort: 8000
