---
- name: "Create or update Web Deployment"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '../templates/web-deployment.yml') }}"

- name: "Create or update Web Service"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '../templates/web-service.yml') }}"

- name: "Create or update Web Route"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', '../templates/web-route.yml') }}"
