name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  tox:
    name: Run unit tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Kerberos development libraries
        run: sudo apt-get update && sudo apt-get install -y libkrb5-dev

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run Tests
        run: |
          poetry run tox
